---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: >
  (?x)^(
    .devcontainer/devcontainer.json|
    .vscode/extensions.json|
    .vscode/settings.json|
  )$
repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.7.0
    hooks:
      - id: cspell
        exclude: >
          (?x)^(
            \.github/CODEOWNERS|
            \.github/workflows/.*\.yml|
            \.gitignore|
            \.pre-commit-config\.yaml|
          )$
        # entry: codespell --relative
        # args: [--relative, --no-progress, --no-summary]
        name: Spell check with cspell
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args:
          - "--config=.config/markdownlint.yaml"
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint
