services:
  onchain-exporter:
    build:
      context: .
    container_name: eigenlayer-onchain-exporter
    expose:
      - "9090"
    restart: unless-stopped
    command: ["eoe", "run", "--config", "/app/eoe-config.yml"]
    volumes:
     - ./eoe-config.yml:/app/eoe-config.yml

  prometheus:
    container_name: eoe-prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - onchain-exporter
    restart: unless-stopped
