name: Publish Docker image

on:
  workflow_dispatch:

jobs:
  publish-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Docker image tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "latest")
          echo "tag=$TAG" >> $GITHUB_ENV
      - name: Build and push image to GitHub Container Registry
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 \
            -f Dockerfile \
            -t "ghcr.io/${{ github.repository_owner }}/eigenlayer-oe:${{ env.tag }}" \
            . --push
